(() => {
  const $ = id => document.getElementById(id);
  $('calc-run').onclick = () => { const v=$('calc-input').value; $('calc-result').textContent=/^[0-9+*/().%\s-]+$/.test(v) ? 'Result: '+Function('return ('+v+')')() : 'Use numbers and basic operators only.'; };
  const clips=JSON.parse(localStorage.getItem('dof-demo-clips')||'[]'); const list=$('clip-list'); const draw=()=>list.innerHTML=clips.map(x=>'<li>'+x.replace(/[<>&]/g,'')+'</li>').join(''); draw(); $('clip-save').onclick=()=>{const v=$('clip-input').value.trim();if(v){clips.unshift(v);localStorage.setItem('dof-demo-clips',JSON.stringify(clips.slice(0,8)));$('clip-input').value='';draw();}};
  $('media-file').onchange=e=>{const f=e.target.files[0];if(f){$('media-player').src=URL.createObjectURL(f);$('media-player').play().catch(()=>{});}};
  let recorder,chunks=[]; $('record-start').onclick=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(s);chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{$('recording').src=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));s.getTracks().forEach(t=>t.stop());};recorder.start();$('record-status').textContent='Recording…';$('record-start').disabled=true;$('record-stop').disabled=false;}catch{$('record-status').textContent='Microphone permission was not granted.';}}; $('record-stop').onclick=()=>{recorder.stop();$('record-status').textContent='Recording ready to play.';$('record-start').disabled=false;$('record-stop').disabled=true;};
  $('image-file').onchange=e=>{const f=e.target.files[0];if(f){const i=$('image-preview');i.src=URL.createObjectURL(f);i.hidden=false;}}; $('brightness').oninput=e=>$('image-preview').style.filter='brightness('+e.target.value+'%)';
  $('nova-run').onclick=()=>{const q=$('nova-input').value.toLowerCase();const r=q.includes('time')?'It is '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):q.includes('help')?'Try asking for the time, or say hello.':q.includes('hello')?'Hello. How can I help?':'This web demo supports hello, help, and time.';$('nova-result').textContent=r;if('speechSynthesis'in window)speechSynthesis.speak(new SpeechSynthesisUtterance(r));};
})();
